PyTorch 是基于以下两个目的而打造的python科学计算框架：  

1.无缝替换NumPy，并且通过利用GPU的算力来实现神经网络的加速。  
2.通过自动微分机制，来让神经网络的实现变得更加容易。

# 张量

In [1]:
import torch
import numpy as np

## 张量初始化

In [3]:
# 1.直接生成张量
data=[[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# 2.通过numpy数组来生成张量
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
# 3. 通过已有张量来生成新的张量
x_ones = torch.zeros_like(x_data)                        # 保留 x_data 的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)   # 重写 x_data 的数据类型：int -> float
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.8365, 0.6905],
        [0.2686, 0.8446]]) 



In [10]:
# 4.通过指定维度来生成张量
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9968, 0.4673, 0.7886],
        [0.5662, 0.2553, 0.6965]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 张量属性

In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")                       #   tensor形状
print(f"Datatype of tensor: {tensor.dtype}")                    #   tensor的数据类型
print(f"Device tensor is stored on: {tensor.device}")           #   tenosr存储的设备

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量运算

In [13]:
# 判断当前环境GPU是否可用, 然后将tensor导入GPU内运行
if torch.cuda.is_available():
  tensor = tensor.to('cuda')


In [14]:
#   1.张量的索引与切片
tensor = torch.ones(4, 4)
tensor[:,1] = 0            # 将第1列(从0开始)的数据全部赋值为0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
#   2.张量的拼接
t=torch.rand(2,3,4)
t1 = torch.cat([t,t,t],dim=2)       #   dim的含义为从0到最后一维，指定为x，则x对应可变化，其他不变
print(t1)

tensor([[[0.1465, 0.7326, 0.5354, 0.5141, 0.1465, 0.7326, 0.5354, 0.5141,
          0.1465, 0.7326, 0.5354, 0.5141],
         [0.6054, 0.1451, 0.0576, 0.1004, 0.6054, 0.1451, 0.0576, 0.1004,
          0.6054, 0.1451, 0.0576, 0.1004],
         [0.7004, 0.4670, 0.2771, 0.7022, 0.7004, 0.4670, 0.2771, 0.7022,
          0.7004, 0.4670, 0.2771, 0.7022]],

        [[0.8731, 0.4714, 0.9162, 0.8621, 0.8731, 0.4714, 0.9162, 0.8621,
          0.8731, 0.4714, 0.9162, 0.8621],
         [0.2139, 0.6196, 0.7642, 0.2327, 0.2139, 0.6196, 0.7642, 0.2327,
          0.2139, 0.6196, 0.7642, 0.2327],
         [0.0534, 0.7622, 0.8668, 0.2437, 0.0534, 0.7622, 0.8668, 0.2437,
          0.0534, 0.7622, 0.8668, 0.2437]]])


In [22]:
# 3.张量的乘法与矩阵的乘法
# 逐个元素相乘结果
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
# 等价写法:
print(f"tensor * tensor: \n {tensor * tensor}")


tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
# 张量与张量的矩阵乘法
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
# 等价写法:
print(f"tensor @ tensor.T: \n {tensor @ tensor.T}")


tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [25]:
#   4.自动赋值运算
print(tensor, "\n")
tensor.add_(5)
print(tensor)
#   自动赋值运算虽然可以节省内存, 但在求导时会因为丢失了中间过程而导致一些问题, 所以我们并不鼓励使用它。

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## tensor与numpy的转化

In [28]:
#   1. 由张量变换为Numpy array数组
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
# 修改张量的值，numpy也会改变
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [31]:
# 2. 由Numpy array数组转为张量
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")
# 修改Numpy array数组的值，则张量值也会随之改变。
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# 神经网络

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square, you can specify with a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [34]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight


10
torch.Size([6, 1, 5, 5])


In [39]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)


tensor([[ 0.0332,  0.0691, -0.0090, -0.0227,  0.0895, -0.0058,  0.1316, -0.0717,
          0.1441,  0.0410]], grad_fn=<AddmmBackward0>)


In [40]:
#   使用随机梯度将所有参数和反向传播的梯度缓冲区归零
net.zero_grad()
out.backward(torch.randn(1, 10))